Remove unused variable in metrics_daemon_test.cc.
x86-generic ASAN builder unittest failed at
metrics_daemon_test.cc:33:18: error: unused variable 'kSecondsPerDay'.
Hopefully this can fix the failure.

BUG=chromium:364818
TEST=NONE

Change-Id: Icb63ed50a285e5f9a522d9dc2a7ab98f4affbf74
Reviewed-on: https://chromium-review.googlesource.com/195557
Reviewed-by: Kuang-che Wu <kcwu@chromium.org>
Commit-Queue: Wu-Cheng Li <wuchengli@chromium.org>
Tested-by: Wu-Cheng Li <wuchengli@chromium.org>
Reviewed-by: Daniel Erat <derat@chromium.org>